### ISSUE TITLE
Image gallery not created under certain circumstances

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/water-fountains.org#155] opened 2019-03-31 20:49 UTC
if both image/P18 and commons:category are present, commons category is ignored  :(

Just happened with
https://www.wikidata.org/wiki/Q55170432

**Comment by ralfhauser** [comment] 2019-03-31 20:50
once I deleted the P18, nothing shows up anymore

**Comment by mmmatthew** [comment] 2019-03-31 21:07
This is a bug. The problem is that 
1. only the Commons Category **statement** is read right now (the quicklink you defined is not expected) 
2. if no image P18 is defined, then the gallery is not created even if a Commons category exists.

If you check the fountain now, the gallery shows up.

**Comment by ralfhauser** [comment] 2019-03-31 21:12
with https://www.wikidata.org/wiki/Q55170336
![image](https://user-images.githubusercontent.com/1681677/55295184-6dcbf500-540a-11e9-8817-af4498a70977.png)
doesn't work either :(

**Comment by mmmatthew** [comment] 2019-03-31 21:17
As I wrote above: 
> 2. if no image P18 is defined, then the gallery is not created even if a Commons category exists.

**Comment by ralfhauser** [comment] 2019-03-31 21:21
but 2 will go away soon ? (as it is totally confusing / counter-intuitive)

**Comment by mmmatthew** [comment] 2019-03-31 21:24
Yes, it is a bug so it should be fixed.

**Comment by ralfhauser** [comment] 2019-04-01 06:41
Please 
1) fix the bug
2) also honour the commons "quicklink"

**Closed as completed** 2019-04-05 17:47 UTC
Labels: Bug, Verified
